---
# Build a dev box for Python/Django app Madlibs
- hosts: all
  sudo: yes
  vars:
    django_dir: '/vagrant_data/madlibs'
  tasks:
    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - python-pip
        - python-dev 
        - postgresql
        - libpq-dev
        - python-psycopg2
        - git
        - screen
        - pv

    # python packages, need sudo
    - pip: name=virtualenv
    - pip: name=pyyaml
    - pip: name=django version=1.8.4 state=present
    - pip: name=whitenoise

    # heroku toolbelt
    - name: Install python-software-properties for apt-add-repository command
      sudo: yes
      action: apt pkg=python-software-properties state=installed
      tags: heroku

    - name: Add Heroku release key for package verification
      sudo: yes
      action: apt_key url=https://toolbelt.heroku.com/apt/release.key state=present
      tags: heroku

    - name: Add Heroku APT repository
      tags: heroku
      sudo: yes
      action: apt_repository repo="deb http://toolbelt.heroku.com/ubuntu ./" state=present

    - name: Install Heroku toolbelt
      tags: heroku
      sudo: yes
      action: apt name=heroku-toolbelt state=latest update_cache=yes cache_valid_time=86400

    # postgreSQL db and user
    - name: Create psql database 
      sudo: yes
      sudo_user: postgres
      postgresql_db: name=madlibs

    - name: Create database user
      sudo: yes
      sudo_user: postgres
      postgresql_user: db=madlibs name=muser password=mpass priv=ALL

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted